name: Java CI with Maven

on:
  push:
    branches: [ master ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build with Maven and Run JUnit Tests
      run: |
          mvn -B package --file pom.xml
          mvn -B test
        
  deploy:
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v2
          - name: Build and Deploy
            run: |
              ./gradlew build
              git config --global user.name "Enagbem"
              git config --global user.email "enoch.kumanyenu99@yahoo.com"
              git checkout -B gh-pages
              git add -f build/
              git commit -m "Build and deploy to gh-pages"
              git push origin gh-pages --force-with-lease
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

  
